config-server:
  name: local
spring:
  profile: local
  datasource:
    url: http://localhost:3305/localDb
    username: hong
    password: 1234

message:
  profile: local
  server-name: "[local] hello world !!!@@"
