config-server:
  name: prod
spring:
  profile: prod
  datasource:
    url: http://localhost:3307/prodDb
    username: hong
    password: 1234

message:
  profile: prod
  server-name: "[prod] hello world ~!~!"
