config-server:
  name: prod
spring:
  profile: prod
  datasource:
    url: http://localhost:3307
    username: hong
    password: 1234

message:
  profile: prod
  server-name: "hello world"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
