config-server:
  name: local
spring:
  profile: local
  datasource:
    url: http://localhost:3306
    username: hong
    password: 1234

message:
  profile: local
  server-name: "hello world"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
