config-server:
  name: dev
spring:
  profile: dev
  datasource:
    url: http://localhost:3306
    username: hong
    password: 1234
message:
  profile: dev
  server-name: "hello world"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
