spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mz-khhong/spring-cloud-config-server.git
          default-label: master

server:
  port: 8090


